version: "3.3"
   
services:
  db:
    image: postgres
    volumes:
        - ./database/database.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
  web:
    build: .
    command: ./bin/chatroom
    ports:
      - "8080:8080"
    depends_on:
      - db
